#+TITLE: Enabling high throughput quantitative metallography for complex microstructures with deep semantic segmentation models: a case study in ultrahigh carbon steel
#+AUTHOR: 

#+OPTIONS:   H:4 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:nil pri:nil tags:not-in-toc

# use figure* environments for figures that should span both columns
# #+LaTeX_CLASS_OPTIONS: [twocolumn]

#+LATEX_HEADER: \usepackage{microtype}
#+LATEX_HEADER: \usepackage[utf8]{inputenc}
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \usepackage{subcaption}
#+LATEX_HEADER: \graphicspath{{figures/}}

#+LATEX_HEADER: \usepackage[backref=true,backend=biber,sorting=none,citestyle=numeric-comp]{biblatex}
# #+LATEX_HEADER: \usepackage[backend=biber,bibencoding=ascii,language=auto,bibstyle=nature,citestyle=numeric-comp,url=true, doi=true,sorting=none, maxbibnames=10,natbib=true]{biblatex}
#+LATEX_HEADER: \addbibresource{uhcs-segment.bib}
# \renewcommand*{\bibfont}{\scriptsize}
#+LATEX_HEADER: \hypersetup{colorlinks=true}


#+BEGIN_ABSTRACT
We apply a deep convolutional neural network segmentation model to enable novel automated microstructure segmentation applications for complex microstructures typically evaluated manually and subjectively.
We explore two microstructure segmentation tasks in an openly-available ultrahigh carbon steel microstructure dataset cite:uhcsdb: segmenting cementite particles in the spheroidized matrix, and segmenting larger fields of view featuring grain boundary carbide, spheroidized particle matrix, particle-free grain boundary denuded zone, Widmanstätten cementite.
We also demonstrate how these data-driven microstructure segmentation models can be combined to obtain empirical cementite particle size distributions from more complex micrographs containing multiple microconstituents.
#+END_ABSTRACT

* Introduction
Openly available microstructure dataset cite:uhcsdb,hecht2016,hecht2017.

Our primary contributions are:
- Establishing two novel microstructure segmentation benchmark datasets
- Connecting microstructure science to the deep semantic segmentation literature
- Exploring novel means of expanding contemporary quantitative microstructure measurement techniques to more complex structures

* Methods
** Segmentation model
*** PixelNet architecture
We use a PixelNet cite:bansal2017 architecture.
General description of training with sparse upsampling (link to our to-be-published implementation in a footnote).
General description of inference with dense upsampling.
Brief comparison with e.g. SegNet.
Motivation: training from scratch on a small dataset.

- BatchNorm - Conv - ReLU layers
- Specify layer configurations, including skip connections

TODO: update architecture schematic with learned-from-scratch models, and s/VGG/conv/

\begin{figure}[!htbp]
  \frame{
  \includegraphics[width=\textwidth]{architecture-scratch}}
  \caption{Inspiration: PixelNet. Top: semantic microstructure segmentation based on manually annotated UHCS microconstituents, including proeutectoid grain boundary cementite (light blue), ferritic matrix (dark blue), spheroidite particles (yellow), and Widmanstätten cementite (green).}
  \label{fig:architecture}
\end{figure}

*** Training
- Initialization
- Pixel sampling strategies (random vs balanced? whatever we stick with...)
- Adam (or SGD+Nesterov with cyclic learning rate if it works?) (specify learning rate, etc).
- Dropout and regularization (weight decay)
- Specify loss function
- Label smoothing (if any in the final version)
- Document data augmentation (rotation with mirror padding/boundary conditions, flips, and scaling for now)

** Semi-automated spheroidite particle annotation
Matt's ActaMat paper cite:hecht2017; describe ImageJ workflow.

** Manual labeling for abstract microconstituent segmentation
We manually labeled a subset of the UHCS dataset cite:uhcsdb,uhcsdata using the open source medical image annotation toolkit MITK cite:mitk.

** Performance evaluation
We report the standard evaluation metrics for semantic segmentation tasks: pixel accuracy (AC) and region intersection over union (IU), both for individual classes and averaged over all four microstructure classes.
For each of these metrics, a higher score indicates better performance.
The intersection over union metric $IU(c)$ for class $c$ is the ratio of correctly predicted pixels of class $c$ to the union of pixels with either ground truth or predicted class $c$:

\begin{equation}
IU(c) = \frac{\sum_i (o_i == c \land y_i == c)}{\sum_i (o_i == c \lor y_i == c) }
\end{equation}

where $\land$ denotes logical conjunction (logical and) and $\lor$ denotes inclusive disjunction (logical or), $o_i$ are the predictions for each pixel $i$, and $y_i$ are the ground truth labels for each pixel.

For the spheroidite particle segmentation task, we also report performance metrics comparing particle size distributions obtained from the model predictions with those obtained from the ground truth annotations (as reported in cite:hecht2017.
The PSD KS metric indicates failure rates for  the two-sample Kolmogorov-Smirnov test to each pair of model and ground truth PSDs (lower is better).

** Computing denuded zone widths

Input: microconstituent prediction map.
We quantify the width of the denuded zone by computing for each matrix-particle interface pixel the minimum distance to the network phase.
In practice we compute a map of euclidean distance to the network phase, and select the measurements at the denuded zone interface.

To obtain the denuded zone interface, we apply several image processing techniques to clean up the microconstituent prediction map, so that only the matrix predictions associated with the diffusion-limited denuded zone adjacent to the proeutectoid cementite network remain.
A morphological filling operation removes any matrix pixels within the network.
Matrix regions that are not connected to the network by applying a morphological closing to matrix phase and removing matrix segments that do not intersect the network phase.
Finally, we remove any matrix predictions that are closer to a widmanstatten region than to a network region, and subsequently remove the widmanstatten regions.
The region boundaries on the cleaned up label image (shown in Figure \ref{fig:denuded_zone}) include only the interface of the proeutectoid cementite network phase (indicated in blue) and the diffuse interface of the denuded zone (indicated in yellow).


* Results and Discussion
TODO: add validation predictions for the entire dataset as supplemental figures?
  
** Semantic microconstituent segmentation
Big question: how many micrographs do I need to annotate to get good perf?
Should we try to answer this question in the current study, or down the road a bit?

\begin{figure}[!htbp]
  \includegraphics[width=\textwidth]{validation_predictions_uhcs_03}
  \caption{Validation set predictions for the complex microconstituent segmentation task.}
  \label{fig:microconstituentresults}
\end{figure}


#+CAPTION: Semantic segmentation performance averaged over validation images. Uncertainties are sample standard deviations calculated across validation folds.
#+NAME: tab:semanticsegmentationperf
| metric            | {1_2,2_2,3_3,4_3,5_3} | {1_2,2_2,3_3,4_3,5_3,7} |
|-------------------+-----------------------+-------------------------|
| matrix            | 64.7 $\pm$ 12.1       | 63.7 $\pm$ 10.2         |
| network           | 86.0 $\pm$ 15.6       | 85.5 $\pm$ 17.8         |
| spheroidite       | 90.5 $\pm$ 7.4        | 89.8 $\pm$ 7.1          |
| widmanstätten      | 40.0 $\pm$ 18.6       | 31.1 $\pm$ 14.9         |
| IU_{avg}          | 69.8 $\pm$ 11.2       | 68.8 $\pm$ 10.9         |
| AC                | 91.6 $\pm$ 6.6        | 90.9 $\pm$ 6.6          |


** Spheroidite particle segmentation
\begin{figure}[!htbp]
  \includegraphics[width=\textwidth]{psd_run04}
  \caption{Independent test set predictions for the spheroidite particle segmentation task.}
  \label{fig:spheroiditeresults}
\end{figure}

TODO: consider watershedding particle prediction maps before comparing PSD with annotations.

#+CAPTION: Segmentation performance on validation sets
#+NAME: tab:particlesegmentationperf
| model                            | matrix         | spheroidite     | IU_{avg}       | AC             | PSD KS |
|----------------------------------+----------------+-----------------+----------------+----------------+--------|
| otsu                             | 86.2 $\pm$ 7.2 | 53.7 $\pm$ 12.1 | 69.9 $\pm$ 9.3 | 88.1 $\pm$ 6.1 | -      |
| thresholded blur\cite{hecht2017} | -              | -               | -              | -              | -      |
|----------------------------------+----------------+-----------------+----------------+----------------+--------|
| {1_2,2_2,3_3,4_3,5_3}            | 91.7 $\pm$ 2.7 | 56.8 $\pm$ 13.8 | 74.2 $\pm$ 7.9 | 92.5 $\pm$ 2.5 | 0.21   |
| {1_2,2_2,3_3,4_3,5_3,7}          | 91.5 $\pm$ 3.0 | 56.7 $\pm$ 12.2 | 74.1 $\pm$ 7.2 | 92.3 $\pm$ 2.8 | 0.125  |


** Automated measurement of abstract microstructure features
# note: change this to input, class predictions, masked particle predictions.
# use the same micrographs as in the abstract microstructure segmentation task.
\begin{figure}[!htbp]
  \includegraphics[width=\textwidth]{combined_model_run01}
  \caption{Independent test set predictions for spheroidite segmentation results in micrographs with multiple microconstituents.}
  \label{fig:fused}
\end{figure}

TODO: add a figure showing measured particle size distributions from Figure \ref{fig:fused}.


\begin{figure}[!htbp]
  \includegraphics[width=\textwidth]{denuded_zone_run05}
  \caption{Denuded zone width distribution measured from semantic microconstituent prediction map. The network interface is shown in blue and the particle matrix interface is shown in yellow.}
  \label{fig:denuded_zone}
\end{figure}

TODO: add a figure comparing measured denuded zone widths using ground truth maps and validation set predictions as input.
Compare with Matt's manual annotations where appropriate?

* Conclusions

\section*{Acknowledgements}
We gratefully acknowledge funding for this work through National Science Foundation grants DMR-1307138 and DMR-1501830, and through the John and Claire Bertucci Foundation.
The UHCS micrographs were graciously provided by Matthew Hecht, Yoosuf Picard, and Bryan Webler (CMU) cite:uhcsdb.
Semantic microstructure annotations were performed by B.D.
The spheroidite annotations were graciously provided by Matthew Hecht and Txai Sibley.
The open source software projects Scikit-Learn cite:sklearn and keras cite:keras were essential to this work.

\printbibliography
